apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce      # ← doit correspondre au PV
  volumeMode: Filesystem # ← doit correspondre au PV
  storageClassName: standard  # ← doit correspondre au PV
  resources:
    requests:
      storage: 5Gi       # ← doit être <= capacité du PV
